knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: app_google_login_callback
            redirect_params: {}



            # user_response: App\Entity\User
            # options:
            #     access_type: offline
            #     scope: 'https://www.googleapis.com/auth/userinfo.email'
